name: Pull Request Inline Code Review

on:
  pull_request:
    types: [opened, synchronize]
    
permissions:
  pull-requests: write

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: pip install requests

      - name: Post Inline Comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          python <<EOF
          import requests
          import os

          GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
          REPO = os.getenv("GITHUB_REPOSITORY")
          PULL_NUMBER = os.getenv("PULL_REQUEST_NUMBER")
          HEAD_SHA = os.getenv("HEAD_SHA")
          FILE_PATH = "src/example.py"
          COMMENT_BODY = "이 부분에서 변수 이름을 직관적으로 바꾸는 게 어떨까요?"

          def post_comment(line):
              url = f"https://api.github.com/repos/{REPO}/pulls/{PULL_NUMBER}/comments"
              headers = {
                  "Authorization": f"token {GITHUB_TOKEN}",
                  "Accept": "application/vnd.github.v3+json"
              }
              data = {
                  "body": COMMENT_BODY,
                  "commit_id": HEAD_SHA,
                  "path": FILE_PATH,
                  "side": "RIGHT",
                  "line": line
              }
              response = requests.post(url, headers=headers, json=data)
              if response.status_code == 201:
                  print(f"Comment added to line {line}")
              else:
                  print(f"Failed to add comment to line {line}: {response.content}")

          for line in range(10, 15):  # 10~14줄에 코멘트 작성
              post_comment(line)
          EOF

